# Generated by Django 5.0.13 on 2025-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sathi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_expenditure",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="risk_tolerance",
            field=models.CharField(default="medium", max_length=50),
        ),
    ]
