# Generated by Django 5.0.13 on 2025-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sathi", "0002_expense_description_userprofile_total_expenditure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="goal",
            new_name="investment_goals",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="monthly_income",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="savings_goal",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="risk_tolerance",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=50,
            ),
        ),
    ]
